#  _____    ___    ____    _____  __  __
# |  ___|  / _ \  |  _ \  |_   _| \ \/ /
# | |_    | | | | | |_) |   | |    \  /
# |  _|   | |_| | |  _ <    | |    /  \
# |_|      \___/  |_| \_\   |_|   /_/\_\

# If you've got any problems, please go to https://reports.fortx.top/ and read the documentation.
# Our discord: https://discord.gg/fortx

# Default off
debug: false

multiserver:
  enabled: false # Enable multiserver support (requires a redis database)


# If multiserver is enabled, you need to set up a Redis database.
redis:
  host: "localhost"
  port: 2137
  password: "fortx_on_top123"
  channels:
    adminchat: "adminchat"
    report: "report"
    helpop: "helpop"

# If multiserver is enabled, change this to the name of your server.
server:
  name: "lobby" # The name of your server, used for multiserver support.

report:
  cooldown: 300 # Cooldown in seconds for a player to send another report.

